.PHONY: clean All

All:
	@echo "----------Building project:[ Lecture11_Example2 - Debug ]----------"
	@cd "Lecture11_Example2" && "$(MAKE)" -f  "Lecture11_Example2.mk"
clean:
	@echo "----------Cleaning project:[ Lecture11_Example2 - Debug ]----------"
	@cd "Lecture11_Example2" && "$(MAKE)" -f  "Lecture11_Example2.mk" clean
