.PHONY: clean All

All:
	@echo "----------Building project:[ Lecture12_Example3 - Debug ]----------"
	@cd "Lecture12_Example3" && "$(MAKE)" -f  "Lecture12_Example3.mk"
clean:
	@echo "----------Cleaning project:[ Lecture12_Example3 - Debug ]----------"
	@cd "Lecture12_Example3" && "$(MAKE)" -f  "Lecture12_Example3.mk" clean
