.PHONY: clean All

All:
	@echo "----------Building project:[ Lecture13_Example2 - Debug ]----------"
	@cd "Lecture13_Example2" && "$(MAKE)" -f  "Lecture13_Example2.mk"
clean:
	@echo "----------Cleaning project:[ Lecture13_Example2 - Debug ]----------"
	@cd "Lecture13_Example2" && "$(MAKE)" -f  "Lecture13_Example2.mk" clean
